# -*- coding: utf-8 -*-
#
# This file created with KivyCreatorProject
# <https://github.com/HeaTTheatR/KivyCreatorProgect
#
# Copyright © 2017 Easy
#
# For suggestions and questions:
# <kivydevelopment@gmail.com>

# LICENSE: MIT

#:import MDIconButton kivymd.button.MDIconButton

<Network>:
    name: 'network'

    BoxLayout:
        orientation:'vertical'
        TextInput:
        Widget:
        Widget:
        Widget:
        Widget:
        Widget:
