# -*- coding: utf-8 -*-
#
# This file created with KivyCreatorProject
# <https://github.com/HeaTTheatR/KivyCreatorProgect
#
# Copyright © 2017 Easy
#
# For suggestions and questions:
# <kivydevelopment@gmail.com>
#
# LICENSE: MIT

<Scan>:
    name: 'scan'

    BoxLayout:

        orientation:'vertical'
        Label:
            color:0,0,0,1
            text:'scan QR or just place device near NFC.'
        Widget:
        Widget:
        Widget: